apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  labels:
    app.kubernetes.io/part-of: aurora-aiops-demo
  name: aurora-aiops-demo-ingress
spec:
  blocks:
    - start: 10.0.0.240
      stop: 10.0.0.245
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  labels:
    app.kubernetes.io/part-of: aurora-aiops-demo
  name: aurora-aiops-demo-ingress
spec:
  interfaces:
    - ^enp2s0$
  loadBalancerIPs: true
