apiVersion: v1
kind: Service
metadata:
  name: kubejojo
  namespace: kubejojo
  labels:
    app.kubernetes.io/name: kubejojo
spec:
  selector:
    app.kubernetes.io/name: kubejojo
  ports:
  - port: 8080
    targetPort: 8080
