apiVersion: v1
kind: Service
metadata:
  name: aurora-aiops
  namespace: aurora-aiops
  labels:
    app.kubernetes.io/name: aurora-aiops
spec:
  selector:
    app.kubernetes.io/name: aurora-aiops
  ports:
  - port: 8080
    targetPort: 8080
